#include "ESPManager.h"
#ifdef ESP8266
#include <ESP8266WiFi.h>
#include <ESP8266httpUpdate.h>
#else
#include <WiFi.h>
#include <HTTPUpdate.h>
#endif
#include <WiFiManager.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
static WiFiClient net,otaNet;static PubSubClient mq(net);static WiFiManager wm;ESPManagerClass ESPManager;static String base(){return String("espmanager/")+ESPMANAGER_DEVICE_ID;}static void rx(char*t,byte*p,unsigned n){String s;for(unsigned i=0;i<n;i++)s+=(char)p[i];ESPManager.handleCommand(t,s);}static ESPManagerClass::E makeE(const char*t,const char*i,const char*n,const char*u){ESPManagerClass::E e;e.type=t;e.id=i;e.name=n;e.uid=u;return e;}
void ESPManagerClass::onCommand(CommandHandler h){cb=h;}void ESPManagerClass::registerSensor(const char*i,const char*n,const char*u,const char*un,const char*d,const char*s,const char*v){if(ec>=32)return;auto&e=es[ec++];e=makeE("sensor",i,n,u);e.unit=un;e.dc=d;e.sc=s;e.vt=v;if(mq.connected())discovery();}void ESPManagerClass::registerBinarySensor(const char*i,const char*n,const char*u,const char*d){if(ec>=32)return;auto&e=es[ec++];e=makeE("binary_sensor",i,n,u);e.dc=d;if(mq.connected())discovery();}void ESPManagerClass::registerSwitch(const char*i,const char*n,const char*u){if(ec<32){es[ec++]=makeE("switch",i,n,u);if(mq.connected())discovery();}}void ESPManagerClass::registerNumber(const char*i,const char*n,const char*u,float lo,float hi,float st,const char*un){if(ec>=32)return;auto&e=es[ec++];e=makeE("number",i,n,u);e.lo=lo;e.hi=hi;e.step=st;e.unit=un;if(mq.connected())discovery();}void ESPManagerClass::registerCover(const char*i,const char*n,const char*u,bool p){if(ec>=32)return;auto&e=es[ec++];e=makeE("cover",i,n,u);e.pos=p;if(mq.connected())discovery();}bool ESPManagerClass::publishState(const char*i,const String&v,bool r){return mq.connected()&&mq.publish((base()+"/state/"+i).c_str(),v.c_str(),r);}void ESPManagerClass::publishSensor(const char*k,double v){char b[32];snprintf(b,sizeof(b),"%.3f",v);if(mq.connected())mq.publish((base()+"/sensor/"+k).c_str(),b,true);}
void ESPManagerClass::discovery(){for(uint8_t k=0;k<ec;k++){auto&e=es[k];JsonDocument d;d["name"]=e.name;d["unique_id"]=e.uid;d["state_topic"]=base()+"/state/"+e.id;d["availability_topic"]=base()+"/availability";if(e.unit.length())d["unit_of_measurement"]=e.unit;if(e.dc.length())d["device_class"]=e.dc;if(e.sc.length())d["state_class"]=e.sc;if(e.vt.length())d["value_template"]=e.vt;if(e.type=="switch"||e.type=="number"||e.type=="cover")d["command_topic"]=base()+"/cmd/entity/"+e.id;if(e.type=="number"){d["min"]=e.lo;d["max"]=e.hi;d["step"]=e.step;}if(e.type=="cover"&&e.pos){d["position_topic"]=base()+"/state/"+e.id+"_position";d["set_position_topic"]=base()+"/cmd/entity/"+e.id+"_position";}JsonArray ids=d["device"]["identifiers"].to<JsonArray>();ids.add(ESPMANAGER_DEVICE_ID);d["device"]["name"]=ESPMANAGER_DEVICE_ID;d["device"]["manufacturer"]="ESP Manager";d["device"]["sw_version"]=ESPMANAGER_FW_VERSION;String p;serializeJson(d,p);String t=String("homeassistant/")+e.type+"/"+ESPMANAGER_DEVICE_ID+"/"+e.id+"/config";mq.publish(t.c_str(),p.c_str(),true);}}
void ESPManagerClass::begin(){Serial.begin(115200);WiFi.mode(WIFI_STA);WiFi.setAutoReconnect(true);WiFi.persistent(true);wm.setConfigPortalBlocking(false);bool ok=wm.autoConnect((String("ESPManager-")+ESPMANAGER_DEVICE_ID).c_str());portal=!ok;ws=ok?OK:PORTAL;if(!ok)lost=millis();mq.setServer(ESPMANAGER_MQTT_HOST,ESPMANAGER_MQTT_PORT);mq.setBufferSize(4096);mq.setCallback(rx);mqttConnect();}void ESPManagerClass::mqttConnect(){if(mq.connected()||WiFi.status()!=WL_CONNECTED||millis()-lastMqtt<5000)return;lastMqtt=millis();String id=String("esp-")+ESPMANAGER_DEVICE_ID;bool ok=String(ESPMANAGER_MQTT_USER).length()?mq.connect(id.c_str(),ESPMANAGER_MQTT_USER,ESPMANAGER_MQTT_PASS,(base()+"/availability").c_str(),0,true,"offline"):mq.connect(id.c_str(),(base()+"/availability").c_str(),0,true,"offline");if(ok){mq.publish((base()+"/availability").c_str(),"online",true);mq.subscribe((base()+"/cmd/#").c_str());discovery();status();}}
void ESPManagerClass::startPortal(){if(portal)return;WiFi.mode(WIFI_AP_STA);wm.startConfigPortal((String("ESPManager-")+ESPMANAGER_DEVICE_ID).c_str());portal=true;ws=PORTAL;}void ESPManagerClass::stopPortal(){if(!portal)return;wm.stopConfigPortal();WiFi.softAPdisconnect(true);portal=false;}void ESPManagerClass::reconnect(){lastRetry=millis();WiFi.mode(WIFI_AP_STA);WiFi.disconnect(false,false);delay(50);WiFi.begin();}void ESPManagerClass::recovered(){stopPortal();WiFi.mode(WIFI_STA);ws=OK;lost=0;lastRetry=0;mqttConnect();}void ESPManagerClass::loop(){wm.process();unsigned long n=millis();if(WiFi.status()==WL_CONNECTED){if(ws!=OK||portal)recovered();mqttConnect();mq.loop();if(n-lastStatus>30000)status();return;}if(ws==OK){lost=n;ws=RETRY;}unsigned long age=n-lost;if(ws==RETRY&&age>=60000)startPortal();if((ws==RETRY||ws==PORTAL)&&n-lastRetry>=ESPMANAGER_WIFI_RECONNECT_INTERVAL)reconnect();if(ws!=FINAL&&age>=ESPMANAGER_WIFI_RECOVERY_RESTART_AFTER-60000){stopPortal();WiFi.mode(WIFI_STA);ws=FINAL;reconnect();}if(ws==FINAL&&n-lastRetry>=ESPMANAGER_WIFI_RECONNECT_INTERVAL)reconnect();if(age>=ESPMANAGER_WIFI_RECOVERY_RESTART_AFTER)ESP.restart();}
void ESPManagerClass::entityCommand(const String&t,const String&p){String pre=base()+"/cmd/entity/";if(cb&&t.startsWith(pre))cb(t.substring(pre.length()),p);}void ESPManagerClass::handleCommand(const String&t,const String&p){if(t.startsWith(base()+"/cmd/entity/")){entityCommand(t,p);return;}JsonDocument d;if(deserializeJson(d,p))return;if(String((const char*)(d["token"]|""))!=ESPMANAGER_OTA_TOKEN)return;if(t.endsWith("/cmd/restart"))ESP.restart();if(t.endsWith("/cmd/ota")){String u=d["url"]|"";
#ifdef ESP8266
ESPhttpUpdate.rebootOnUpdate(false);auto r=ESPhttpUpdate.update(otaNet,u);
#else
httpUpdate.rebootOnUpdate(false);auto r=httpUpdate.update(otaNet,u);
#endif
if(r==HTTP_UPDATE_OK)ESP.restart();}}
void ESPManagerClass::status(){lastStatus=millis();JsonDocument d;d["device_id"]=ESPMANAGER_DEVICE_ID;d["firmware_version"]=ESPMANAGER_FW_VERSION;d["ip"]=WiFi.localIP().toString();d["rssi"]=WiFi.RSSI();String o;serializeJson(d,o);mq.publish((base()+"/status").c_str(),o.c_str(),true);}void ESPManagerClass::log(const String&s){Serial.println(s);if(mq.connected())mq.publish((base()+"/log").c_str(),s.c_str());}



