#include "ESPManager.h"
#ifdef ESP8266
#include <ESP8266WiFi.h>
#include <ESP8266httpUpdate.h>
#else
#include <WiFi.h>
#include <HTTPUpdate.h>
#endif
#include <WiFiManager.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
static WiFiClient mqttNet,otaNet;static PubSubClient mq(mqttNet);static WiFiManager wm;ESPManagerClass ESPManager;
static String base(){return String("espmanager/")+ESPMANAGER_DEVICE_ID;}
static void callback(char*t,byte*p,unsigned int n){String s;for(unsigned i=0;i<n;i++)s+=(char)p[i];ESPManager.handleCommand(t,s);}
static void otaReport(const String&s,int p,const String&m){JsonDocument d;d["state"]=s;d["percent"]=p;d["message"]=m;String o;serializeJson(d,o);if(mq.connected())mq.publish((base()+"/ota/progress").c_str(),o.c_str(),true);}
String ESPManagerClass::slug(const String&v)const{String o;for(unsigned i=0;i<v.length();i++){char c=tolower(v[i]);if(isalnum(c))o+=c;else if(o.length()&&o[o.length()-1]!='_')o+='_';}while(o.endsWith("_"))o.remove(o.length()-1);return o;}
bool ESPManagerClass::registerSensor(const char*key,const char*name,const char*uniqueId,const char*unit,const char*deviceClass,const char*stateClass,const char*valueTemplate,bool forceUpdate){if(!key||!name||!uniqueId||sensorCount>=MAX_DISCOVERY_SENSORS)return false;for(uint8_t i=0;i<sensorCount;i++)if(sensors[i].key==key)return true;SensorDef&d=sensors[sensorCount++];d.key=key;d.name=name;d.uniqueId=uniqueId;d.unit=unit;d.deviceClass=deviceClass;d.stateClass=stateClass;d.valueTemplate=valueTemplate;d.forceUpdate=forceUpdate;if(mq.connected())publishDiscovery(d);return true;}
void ESPManagerClass::registerLegacySmartmeter(){if(String(ESPMANAGER_DEVICE_ID)!="smartmeter")return;registerSensor("Zaehlerstand_positiv","Zählerstand_Bezug","smartmeter_kWh_bezug","kWh","energy","total_increasing","{{ value | float / 1000 }}");registerSensor("Zaehlerstand_negativ","Zählerstand_Einspeisung","smartmeter_kWh_einspeisung","kWh","energy","total_increasing","{{ value | float / 1000 }}");registerSensor("Leistung_positiv","Leistung_Bezug","smartmeter_leistung_bezug","W","power","measurement","",true);registerSensor("Leistung_negativ","Leistung_Einspeisung","smartmeter_leistung_einspeisung","W","power","measurement","",true);registerSensor("Leistungsfaktor","Leistungsfaktor","smartmeter_leistungsfaktor","","","measurement");registerSensor("Spannung Phase 1","Spannung L1","smartmeter_spannung_l1","V","voltage","measurement");registerSensor("Spannung Phase 2","Spannung L2","smartmeter_spannung_l2","V","voltage","measurement");registerSensor("Spannung Phase 3","Spannung L3","smartmeter_spannung_l3","V","voltage","measurement");registerSensor("Strom Phase 1","Strom L1","smartmeter_strom_l1","A","current","measurement");registerSensor("Strom Phase 2","Strom L2","smartmeter_strom_l2","A","current","measurement");registerSensor("Strom Phase 3","Strom L3","smartmeter_strom_l3","A","current","measurement");}
void ESPManagerClass::publishDiscovery(const SensorDef&d){JsonDocument c;c["name"]=d.name;c["unique_id"]=d.uniqueId;c["state_topic"]=base()+"/sensor/"+d.key;c["availability_topic"]=base()+"/availability";c["payload_available"]="online";c["payload_not_available"]="offline";if(d.unit.length())c["unit_of_measurement"]=d.unit;if(d.deviceClass.length())c["device_class"]=d.deviceClass;if(d.stateClass.length())c["state_class"]=d.stateClass;if(d.valueTemplate.length())c["value_template"]=d.valueTemplate;if(d.forceUpdate)c["force_update"]=true;JsonArray ids=c["device"]["identifiers"].to<JsonArray>();ids.add(ESPMANAGER_DEVICE_ID);c["device"]["name"]=ESPMANAGER_DEVICE_ID;c["device"]["manufacturer"]="ESP Manager";c["device"]["model"]="Arduino ESP";c["device"]["sw_version"]=ESPMANAGER_FW_VERSION;String payload;serializeJson(c,payload);String topic=String("homeassistant/sensor/")+ESPMANAGER_DEVICE_ID+"/"+slug(d.uniqueId)+"/config";mq.publish(topic.c_str(),payload.c_str(),true);}
void ESPManagerClass::publishDiscovery(){for(uint8_t i=0;i<sensorCount;i++)publishDiscovery(sensors[i]);}
void ESPManagerClass::begin(){Serial.begin(115200);delay(50);registerLegacySmartmeter();WiFi.mode(WIFI_STA);WiFi.setAutoReconnect(true);WiFi.persistent(true);wm.setConfigPortalBlocking(false);wm.setConfigPortalTimeout(0);bool ok=wm.autoConnect((String("ESPManager-")+ESPMANAGER_DEVICE_ID).c_str());portalActive=!ok;wifiState=ok?WIFI_OK:WIFI_PORTAL;if(!ok){wifiLostAt=millis();Serial.println("[ESPManager] WLAN nicht verbunden, Fallback-Portal aktiv");}mq.setServer(ESPMANAGER_MQTT_HOST,ESPMANAGER_MQTT_PORT);mq.setBufferSize(4096);mq.setCallback(callback);mqttConnect();}
void ESPManagerClass::beginWifiRecovery(){if(!wifiLostAt)wifiLostAt=millis();wifiState=WIFI_RETRY;Serial.println("[ESPManager] WLAN verloren, Wiederherstellung gestartet");}
void ESPManagerClass::tryWifiReconnect(const char*r){lastWifiRetry=millis();Serial.printf("[ESPManager] WLAN-Verbindungsversuch: %s\n",r);WiFi.mode(WIFI_AP_STA);WiFi.disconnect(false,false);delay(50);WiFi.begin();}
void ESPManagerClass::startFallbackPortal(){if(portalActive)return;WiFi.mode(WIFI_AP_STA);wm.setConfigPortalBlocking(false);wm.startConfigPortal((String("ESPManager-")+ESPMANAGER_DEVICE_ID).c_str());portalActive=true;wifiState=WIFI_PORTAL;Serial.println("[ESPManager] Fallback-Portal gestartet; STA-Recovery läuft weiter");}
void ESPManagerClass::stopFallbackPortal(){if(!portalActive)return;wm.stopConfigPortal();portalActive=false;WiFi.softAPdisconnect(true);Serial.println("[ESPManager] Fallback-Portal beendet");}
void ESPManagerClass::wifiRecovered(){stopFallbackPortal();WiFi.mode(WIFI_STA);wifiState=WIFI_OK;wifiLostAt=0;lastWifiRetry=0;Serial.println("[ESPManager] WLAN selbstständig wiederhergestellt");mqttConnect();}
void ESPManagerClass::loop(){wm.process();unsigned long now=millis();if(WiFi.status()==WL_CONNECTED){if(wifiState!=WIFI_OK||portalActive)wifiRecovered();mqttConnect();mq.loop();if(now-lastStatus>30000UL)status();return;}if(wifiState==WIFI_OK)beginWifiRecovery();unsigned long outage=now-wifiLostAt;if(wifiState==WIFI_RETRY&&outage>=60000UL)startFallbackPortal();if((wifiState==WIFI_RETRY||wifiState==WIFI_PORTAL)&&now-lastWifiRetry>=ESPMANAGER_WIFI_RECONNECT_INTERVAL)tryWifiReconnect(wifiState==WIFI_PORTAL?"parallel zum Portal":"gespeicherte Zugangsdaten");const unsigned long finalWindow=60000UL,restartAfter=ESPMANAGER_WIFI_RECOVERY_RESTART_AFTER;if(wifiState!=WIFI_FINAL_RETRY&&outage>=restartAfter-finalWindow){stopFallbackPortal();WiFi.mode(WIFI_STA);wifiState=WIFI_FINAL_RETRY;tryWifiReconnect("letzte reine STA-Phase");}if(wifiState==WIFI_FINAL_RETRY&&now-lastWifiRetry>=ESPMANAGER_WIFI_RECONNECT_INTERVAL)tryWifiReconnect("letzte reine STA-Phase");if(outage>=restartAfter){Serial.println("[ESPManager] Kontrollierter Neustart nach WLAN-Ausfall");delay(250);ESP.restart();}}
void ESPManagerClass::mqttConnect(){if(mq.connected()||WiFi.status()!=WL_CONNECTED||millis()-lastMqtt<5000UL)return;lastMqtt=millis();String id=String("esp-")+ESPMANAGER_DEVICE_ID;bool ok=String(ESPMANAGER_MQTT_USER).length()?mq.connect(id.c_str(),ESPMANAGER_MQTT_USER,ESPMANAGER_MQTT_PASS,(base()+"/availability").c_str(),0,true,"offline"):mq.connect(id.c_str(),(base()+"/availability").c_str(),0,true,"offline");if(ok){mq.publish((base()+"/availability").c_str(),"online",true);mq.subscribe((base()+"/cmd/#").c_str());publishDiscovery();status();}}
void ESPManagerClass::status(){lastStatus=millis();JsonDocument d;d["device_id"]=ESPMANAGER_DEVICE_ID;d["firmware_version"]=ESPMANAGER_FW_VERSION;d["ip"]=WiFi.localIP().toString();d["ssid"]=WiFi.SSID();d["rssi"]=WiFi.RSSI();d["uptime"]=millis()/1000UL;d["free_heap"]=ESP.getFreeHeap();d["wifi_recovery_state"]=(int)wifiState;d["wifi_portal"]=portalActive;d["discovery_sensors"]=sensorCount;String o;serializeJson(d,o);mq.publish((base()+"/status").c_str(),o.c_str(),true);}
void ESPManagerClass::log(const String&s){Serial.println(String("[ESPManager] ")+s);if(mq.connected())mq.publish((base()+"/log").c_str(),s.c_str());}
void ESPManagerClass::publishSensor(const char*k,double v){char b[32];snprintf(b,sizeof(b),"%.3f",v);if(mq.connected())mq.publish((base()+"/sensor/"+k).c_str(),b,true);}
void ESPManagerClass::handleCommand(const String&t,const String&p){JsonDocument d;if(deserializeJson(d,p))return;if(String((const char*)(d["token"]|""))!=ESPMANAGER_OTA_TOKEN)return;if(t.endsWith("/cmd/restart"))ESP.restart();if(t.endsWith("/cmd/ota")){String u=d["url"]|"";otaReport("received",0,"Kommando empfangen");
#ifdef ESP8266
ESPhttpUpdate.rebootOnUpdate(false);auto r=ESPhttpUpdate.update(otaNet,u);
#else
httpUpdate.rebootOnUpdate(false);auto r=httpUpdate.update(otaNet,u);
#endif
if(r==HTTP_UPDATE_OK){otaReport("finished",100,"Update vollständig, Neustart folgt");for(int i=0;i<8;i++){mq.loop();delay(100);}ESP.restart();}else otaReport("failed",0,"Update fehlgeschlagen");}}
