name: ESP Manager Dev
version: 0.13.1-dev
slug: esp_manager_dev
description: Arduino-C++ ESP-Projektverwaltung mit MQTT Discovery
arch: [amd64, aarch64, armv7]
startup: services
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:chip
panel_title: ESP Manager Dev
map: [config:rw]
